backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: True
    slug: "{{year}}-{{month}}-{{day}}-{{title | escape}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blogPost"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}